[2023-07-08 18:04:14,662] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 18:04:14] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-08 18:04:14,665] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 18:04:14] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-08 18:04:59,417] ERROR log_exception() L1449 Exception on /buscar_livro_id [GET] - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Projeto\Back-End\app.py", line 95, in buscar_livro_id
    livro_id = query.id
               ^^^^^^^^
AttributeError: 'LivroBuscaSchema' object has no attribute 'id'
[2023-07-08 18:04:59,424] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 18:04:59] "[35m[1mGET /buscar_livro_id?nome=Teste HTTP/1.1[0m" 500 - - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-08 18:05:00,544] ERROR log_exception() L1449 Exception on /buscar_livro_id [GET] - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Projeto\Back-End\app.py", line 95, in buscar_livro_id
    livro_id = query.id
               ^^^^^^^^
AttributeError: 'LivroBuscaSchema' object has no attribute 'id'
[2023-07-08 18:05:00,554] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 18:05:00] "[35m[1mGET /buscar_livro_id?nome=Teste HTTP/1.1[0m" 500 - - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-07-08 18:05:14,203] ERROR log_exception() L1449 Exception on /buscar_livro_id [GET] - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\Downloads\Projeto\Back-End\app.py", line 95, in buscar_livro_id
    livro_id = query.id
               ^^^^^^^^
AttributeError: 'LivroBuscaSchema' object has no attribute 'id'
[2023-07-08 18:05:14,215] INFO _log() L224  127.0.0.1 - - [08/Jul/2023 18:05:14] "[35m[1mGET /buscar_livro_id?nome=Romeu%20e%20Julieta HTTP/1.1[0m" 500 - - call_trace=C:\Users\felip\Downloads\Pós\desenvolvimento-full-stack\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
